### ISSUE TITLE
Locale Support: China and Netherlands

### ISSUE THREAD

**Issue by ronakdesai** [utekaravinash/gopaapi5#1]
China: https://amazon.cn (CNY)
Netherlands: https://www.amazon.nl (EUR)

**Comment by utekaravinash** [comment]
Thanks! Netherlands locale seems to be recently added to the PA API documentation. I'll make required changes in the client library to support it.

But, local reference for China is not available. So, it won't be added to the client library. You can check all available locales here: https://webservices.amazon.com/paapi5/documentation/locale-reference.html

**Comment by utekaravinash** [comment]
Locale support for Netherlands added in release [v1.3.3](https://github.com/utekaravinash/gopaapi5/tree/v1.3.3)
